apiVersion: v1
kind: Service
metadata:
  name: www-dcdn-tk
  labels:
    name: www.dcdn.tk
    app: www.dcdn.tk
spec:
  selector:
    app: www.dcdn.tk 
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
     
