apiVersion: v1
kind: ReplicationController
metadata:
  name: www-dcdn-tk
  labels:
    app: www.dcdn.tk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: www.dcdn.tk
    spec:
        containers:
          - name: mysql
            image: registry.dcdn.tk:5000/mysql
            ports:
              - containerPort: 3306
                name: mysql
                protocol: TCP 
          - name: wordpress
            image: registry.dcdn.tk:5000/wordpress
            ports:
              - containerPort: 80
                name: wordpress
                protocol: TCP

